name: Terraform Pipeline deploy
on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/env/**.tf'
      - 'terraform/env/**.tfvars'
      - 'terraform/modules/**.tf'
  pull_request:
    paths:
      - 'terraform/env/**.tf'
      - 'terraform/env/**.tfvars'
      - 'terraform/modules/**.tf'

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    
    environment: dev
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Terraform Init
        working-directory: terraform/env
        run: terraform init -input=false

      - name: Terraform Format Check
        working-directory: terraform/env
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: terraform/env
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: terraform/env
        run: terraform plan -no-color -out=tfplan.out

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/env/tfplan.out

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: terraform/env
        run: terraform apply -auto-approve tfplan.out

